name: Cart Dev Pipeline
run-name: Cart Dev Pipeline

on:
  push:
    branches-ignore:
      - 'main'

jobs:
  lint:
    runs-on: self-hosted
    steps:
      - run: echo "npx eslint ."

  test:
    needs: lint
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm ci
      - run: npm test

  integration-test:
    needs: test
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm ci
      - run: npm run test:integration
